### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by jihyunleeme** [JAEHEELEE-Cyber/upbit_AutoTrade#1]
안녕하세요. 이메일 주소가 써있었다면 이메일을 드렸을텐데 
연락드릴 길이 없어 이 저장소에 issue를 남깁니다.
https://goodmilktea.tistory.com 블로그 운영자 맞으신가요..
구글링하다 우연하게 블로그를 방문하게 되었는데 저작권 관련 문제가 생긴걸 모르시고 계신거같아서요.
최대한 빨리 로그인하셔서 댓글과 방명록 꼭 확인하셔야 할 것 같습니다.
내용 확인하시면 이 이슈는 삭제하도록 하겠습니다.

**Comment by JAEHEELEE-Cyber** [comment]
안녕하세요. 해당 티스토리 블로그 운영자입니다.
해당 블로그를 한동안 관리하지 않아 전혀 모르고 있었는데
보내주신 메일을 통해 알게 되었습니다. 정말 감사합니다.
해당 게시물은 현재 모두 삭제하였으며 ,
 게시물 저작권자인 강태원 교수님께 연락드렸습니다.

다시 한 번 감사의 말씀 드립니다 ..ㅠㅠ

**Comment by jihyunleeme** [comment]
아하 issue를 등록하면서 자동으로 이메일이 갔나보네요.
확인하셔서 연락도 드렸다니 다행입니다! 잘 해결되셨길 바래요... 
제가 위에서 이 issue삭제한다고 했는데 알고보니 레포지토리 주인만 issue삭제가 가능하네요.
삭제하셔도 됩니다! 그럼.... 이만... 즐거운 코딩하세요: )!
